# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ebffef0c987f0090435d1c24ba4a25700041696faaf70cf1b9fde4120d4995594e5803a6e47433fb35884ca17f1d4076e9ffeb6ad4145f6e4e1c5475e99a875

test:
  secret_key_base: 3d9413ce374902ad4b16ec7923161ecc3df2890e1e7b0e2ada1cf3a96152061408a1892357d87b3d08671b342ddd78fa6ce4758f857eb8e85d4e1c63a53d1418

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
